// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ConvertRequest struct {
	LongUrl string `json: "longUrl"`
}

type ConvertResponse struct {
	ShortUrl string `json: "shortUrl"`
}

type ShowRequest struct {
	ShortUrl string `path: "shortUrl"`
}

type ShowResponse struct {
	LongUrl string `json: "longUrl"`
}
