version: '3'
services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=shortener
      - MYSQL_DATABASE=shortener
      - MYSQL_USER=shortener
      - MYSQL_PASSWORD=shortener